### ISSUE TITLE
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

### ISSUE THREAD

**Issue by guo13947296316** [CurryYuan/InstanceRefer#3]
Hi, CurryYuan:
I have met some problems as below:
Preparing data...
train on 36665 samples and val on 9508 samples
loading data...
loading data...
Initializing...
model params 6857788
Start training...
Epoch 1 starting...
Traceback (most recent call last):
  File "/remote-home/source/46/guopeng/scripts/train.py", line 221, in <module>
    train(CONF)
  File "/remote-home/source/46/guopeng/scripts/train.py", line 211, in train
    solver(args.epoch, args.verbose)
  File "/remote-home/source/46/guopeng/lib/solver.py", line 156, in __call__
    self._feed(self.dataloader["train"], "train", epoch_id)
  File "/remote-home/source/46/guopeng/lib/solver.py", line 248, in _feed
    for idx, data_dict in enumerate(dataloader):
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/remote-home/source/46/guopeng/lib/dataset.py", line 464, in collate_fn
    outputs = sparse_collate_fn(inputs)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/torchsparse-1.1.0-py3.6-linux-x86_64.egg/torchsparse/utils/helpers.py", line 209, in sparse_collate_fn
    dim=0)
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated
I think maybe you know the Bug.

**Comment by BinGoh98** [comment]
> Hi, CurryYuan:
> I have met some problems as below:
> Preparing data...
> train on 36665 samples and val on 9508 samples
> loading data...
> loading data...
> Initializing...
> model params 6857788
> Start training...
> Epoch 1 starting...
> Traceback (most recent call last):
> File "/remote-home/source/46/guopeng/scripts/train.py", line 221, in
> train(CONF)
> File "/remote-home/source/46/guopeng/scripts/train.py", line 211, in train
> solver(args.epoch, args.verbose)
> File "/remote-home/source/46/guopeng/lib/solver.py", line 156, in **call**
> self._feed(self.dataloader["train"], "train", epoch_id)
> File "/remote-home/source/46/guopeng/lib/solver.py", line 248, in _feed
> for idx, data_dict in enumerate(dataloader):
> File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in **next**
> data = self._next_data()
> File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
> return self._process_data(data)
> File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
> data.reraise()
> File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
> raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
> data = fetcher.fetch(index)
> File "/usr/local/miniconda3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
> return self.collate_fn(data)
> File "/remote-home/source/46/guopeng/lib/dataset.py", line 464, in collate_fn
> outputs = sparse_collate_fn(inputs)
> File "/usr/local/miniconda3/lib/python3.6/site-packages/torchsparse-1.1.0-py3.6-linux-x86_64.egg/torchsparse/utils/helpers.py", line 209, in sparse_collate_fn
> dim=0)
> RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated
> I think maybe you know the Bug.

I met this problem too. And I replaced the **/lib/torchparse** with the newest version: https://github.com/mit-han-lab/torchsparse. And it works!
